### ISSUE TITLE
Fix flaky WriterTest#topicCreatorTest

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1003]
```
4360
WriterTest > topicCreatorTest() FAILED
[4361](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4362)
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
[4362](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4363)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[4363](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4364)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
[4364](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4365)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
[4365](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4366)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
[4366](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4367)
        at app//org.astraea.etl.WriterTest.$anonfun$topicCreatorTest$2(WriterTest.scala:48)
[4367](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4368)
        at app//org.astraea.etl.Utils$.Using(Utils.scala:56)
[4368](https://github.com/skiptests/astraea/actions/runs/3324911490/jobs/5497060880#step:5:4369)
        at app//org.astraea.etl.WriterTest.topicCreatorTest(WriterTest.scala:43)
```

**Comment by chia7712** [comment]
fixed by #1013
