### ISSUE TITLE
ReplicaCollieTest can't run on windows

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#102]

**Comment by chia7712** [comment]
@harryteng9527 可否麻煩你著手試試看這個議題？

**Comment by harryteng9527** [comment]
@chia7712 

測試此issue之測試環境為:

`OS: Windows 10 - 64位元`
`Java: JDK11`

### 1. testVerify() 測試及修改

錯誤訊息如下:
```diff
- java.lang.IllegalStateException: java.nio.file.FileSystemException: C:\Users\Harry\AppData\Local\Temp\local_zk_snapshot15401265922398997715\version-2\log.1: 程序無法存取檔案，因為檔案正由另一個程序使用。
- Caused by: java.nio.file.FileSystemException: C:\Users\Harry\AppData\Local\Temp\local_zk_snapshot15401265922398997715\version-2\log.1: 程序無法存取檔案，因為檔案正由另一個程序使用。
```

發現在刪除檔案的時候，有一個java process 正在存取log.1導致無法刪除。

![verify01](https://user-images.githubusercontent.com/90374678/143042602-10843b39-7597-4204-a82f-824a50d5fdc2.jpg)
![資源管理](https://user-images.githubusercontent.com/90374678/143042780-b109ff2b-bc63-4e33-8be4-c4996029d35f.jpg)
由上圖(1)判斷是log檔在要被刪除的當下被某個java process存取，透過[Windows 的資源管理器(如上圖(2))](https://en.wikipedia.org/wiki/Resource_Monitor)觀察後發現確實如此

透過錯誤訊息以及資源管理器的資訊後，深入專案去看code，發現在檔案被close時會將裡面的closed改為true
![close true](https://user-images.githubusercontent.com/90374678/143051786-320f305d-1d8d-45ef-add1-26dbfdc5a91d.jpg)
透過監控查看close值，再刪除檔案前close值一樣為false(即未被closed，導致刪除時還有process在存取欲被刪除之檔案)。
![log close false](https://user-images.githubusercontent.com/90374678/143051114-e29e2ea9-950d-45a6-922b-ab5421499639.jpg)

所以我在刪除的指令前新增close log的指令。
![關閉log](https://user-images.githubusercontent.com/90374678/143043319-27273bc2-8add-4a6d-8503-b391b9e898ae.jpg)

而檔案被存取導致無法刪除之議題，有時會出現有時不會出現，目前還無查出為什麼

### 2. testExecute()
錯誤訊息如下:
```diff
- Unexpected exception thrown.
- org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:56941'.
- Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException: ���ݥD���w�j�������@�Ӳ{�s���s�u�C
	 at com.esotericsoftware.kryo.io.Input.fill(Input.java:148)
	 at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	 at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
- Caused by: java.io.IOException: ���ݥD���w�j�������@�Ӳ{�s���s�u�C
	 at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	 at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	 at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	 at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	 at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
- Unexpected exception thrown.
- org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:56941'.
	 at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
	 at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:333)
	 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	 at java.base/java.lang.Thread.run(Thread.java:834)
- Caused by: java.io.IOException: ���ݥD���w�j�������@�Ӳ{�s���s�u�C
	 at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	 at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	 at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	 at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	 at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	 at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
Task :app:test FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:test'.
- Process 'Gradle Test Executor 52' finished with non-zero exit value 1
```


根據印出的錯誤訊息，為了測試此錯誤與Gradle是否有關，利用[Project settings](https://www.jetbrains.com/help/idea/configure-project-settings.html)把run tests using Gradle改成 run tests using Intellij IDEA後再進行一次單元測試。

![setting](https://user-images.githubusercontent.com/90374678/143044980-f8d8284d-d396-4179-8a72-b7194dd739c5.jpg)
測試結束後，發現 *Process finished with exit code 1*


於是在專案中利用[Search everywhere](https://www.jetbrains.com/help/idea/searching-everywhere.html#search_all)查詢System.exit並設置斷點

![everywhere](https://user-images.githubusercontent.com/90374678/143045567-55164956-117a-42fe-83a8-35ff6f607ec4.jpg)
發現Kafka會keep thread(LogDirFailureHandler) 去看_liveLogDirs().isEmpty() 是否Empty (在此處發生exception)
![livedir](https://user-images.githubusercontent.com/90374678/143046782-0db46b7a-e6f1-4d9b-b823-9dc10a3fae03.jpg)

exception發生後會執行Runtime.getRuntime().exit(status); 導致測試跳出。
![logdir_thread_error](https://user-images.githubusercontent.com/90374678/143045494-669b687f-cd47-48b9-8296-1210b02fecdd.jpg)

我會再查查看問題是出在哪裡，對於解決此議題有無其他方向可以建議，謝謝。

**Comment by chia7712** [comment]
> 由上圖(1)判斷是log檔在要被刪除的當下被某個java process存取，透過Windows 的資源管理器(如上圖(2))觀察後發現確實如此

這個有辦法得知是哪個java process嗎？會不會是我們的關閉過程有bug導致broker過早關閉之類的狀況？

**Comment by harryteng9527** [comment]
@chia7712 
發現是 GradleWorkerMain lock住欲刪除之檔案

從Windows的資源管理器得知:
![資源管理器](https://user-images.githubusercontent.com/90374678/144965887-4cc8a838-2475-4230-8ab2-a74433dbcc2f.jpg)
PID為6540的process會存取log.1

再透過[jps](https://docs.oracle.com/javase/7/docs/technotes/tools/share/jps.html)指令得知目前的java process(6540)是GradleWorkerMain
![jps-1](https://user-images.githubusercontent.com/90374678/144967618-f2a3439b-2ba7-4848-b6ec-0cdc0fdd4f18.jpg)

**Comment by chia7712** [comment]
`GradleWorkerMain` 所以可能是gradle的行為在windows下可能跟linux不太一樣？

**Comment by chia7712** [comment]
已經將相關測試在windows上排除
