### ISSUE TITLE
fix flaky BalancerHandlerTest#testReport

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1030]
```
BalancerHandlerTest > testReport() FAILED
[503](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:504)
    org.opentest4j.AssertionFailedError: expected: not equal but was: <0>
[504](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:505)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
[505](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:506)
        at app//org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:276)
[506](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:507)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:265)
[507](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:508)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:260)
[508](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:509)
        at app//org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:2127)
[509](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:510)
        at app//org.astraea.app.web.BalancerHandlerTest.lambda$testReport$1(BalancerHandlerTest.java:90)
[510](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:511)
        at java.base@11.0.17/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[511](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:512)
        at java.base@11.0.17/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
[512](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:513)
        at java.base@11.0.17/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[513](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:514)
        at java.base@11.0.17/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[514](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:515)
        at java.base@11.0.17/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
[515](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:516)
        at java.base@11.0.17/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[516](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:517)
        at java.base@11.0.17/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[517](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:518)
        at java.base@11.0.17/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[518](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:519)
        at java.base@11.0.17/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[519](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:520)
        at java.base@11.0.17/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[520](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:521)
        at java.base@11.0.17/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[521](https://github.com/skiptests/astraea/actions/runs/3350470875/jobs/5551294953#step:5:522)
        at app//org.astraea.app.web.BalancerHandlerTest.testReport(BalancerHandlerTest.java:90)
```

**Comment by chia7712** [comment]
@garyparrot 有機會的話幫忙看一下
