### ISSUE TITLE
Fix flaky `MetricCollectorTest#metrics`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1136]
https://github.com/skiptests/astraea/actions/runs/3498335527/jobs/5858560841#step:5:2910

```
MetricCollectorTest > metrics() > org.astraea.common.metrics.collector.MetricCollectorTest.metrics()[4] FAILED
    org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at app//org.astraea.common.metrics.collector.MetricCollectorTest.metrics(MetricCollectorTest.java:145)
```

**Comment by garyparrot** [comment]
`MetricCollector` 大改過就沒怎麽看到這個錯誤了，先關閉。
