### ISSUE TITLE
Fix Flaky `TopicHandlerTest#testWithWebService()`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1207]
https://github.com/skiptests/astraea/actions/runs/3602487839/jobs/6069504841#step:5:692

```
TopicHandlerTest > testWithWebService() FAILED
    org.opentest4j.AssertionFailedError: expected: <4> but was: <0>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at app//org.astraea.app.web.TopicHandlerTest.testWithWebService(TopicHandlerTest.java:75)
```

**Comment by garyparrot** [comment]
@chia7712 抱歉想問一個小問題

![image](https://user-images.githubusercontent.com/39105714/205326794-0c554b7d-ff97-4319-9242-754e7340028f.png)

`POST /topics` 在建立完 topic 後會立刻呼叫 Admin 系列的函數去索取建立 topic 的資訊，不過這個過程中有 race condition，Kafka 叢集那邊的資料還沒完全更新完就讀取結果會出現錯誤。

這個 Flaky Test 的源頭是在遇到這個情境時

https://github.com/skiptests/astraea/blob/b53ee26ed808e8a3dcaedaacd833c3db84ad1c49/app/src/main/java/org/astraea/app/web/TopicHandler.java#L195-L200

會直接忽略這個錯誤，然後回傳空的結果，這個是 `POST /topics` 設計的一部分嗎，如果是的話，那我可能要把 `TopicHandler#testWithWebService` 內和 Response 有關的檢查去掉。

**Comment by chia7712** [comment]
> 會直接忽略這個錯誤，然後回傳空的結果，這個是 POST /topics 設計的一部分嗎，如果是的話，那我可能要把 TopicHandler#testWithWebService 內和 Response 有關的檢查去掉。

這隻 API 的回應會吃掉錯誤應該是對應 kafka 無法及時反應 topic creation 的結果，如同 kafka connector API 也有一樣的狀況。我們在測試的部分可能只能針對 name 做檢查，其他的話則要反覆 get 來完成。另外 docs 似乎沒有特別提到這個，方便的話也請一併更新文檔，感恩
