### ISSUE TITLE
Data Directory 的搬移導致 Kafka Broker 內部的錯誤

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1325]
剛剛在做負載平衡時撞到這個問題，有個 Partition 在經過 data directory 的搬移後，經過了很長的時間，他的 `future` flag 一直處於 true 的情況。

![image](https://user-images.githubusercontent.com/39105714/208953745-6c95ca00-13d4-4f68-bc78-1b3964c3d344.png)

檢查一下該 Broker 的 log 後有發現一些錯誤

```
[2022-12-21 15:46:02,842] ERROR [ReplicaAlterLogDirsThread-2]: Unexpected error occurred while processing data for partition topicB-86 at offset 259728 (kafka.server.ReplicaAlterLogDirsThread)
java.lang.IllegalStateException: Offset mismatch for the future replica topicB-86: fetched offset = 259728, log end offset = 0.
        at kafka.server.ReplicaAlterLogDirsThread.processPartitionData(ReplicaAlterLogDirsThread.scala:67)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$7(AbstractFetcherThread.scala:336)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6(AbstractFetcherThread.scala:325)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6$adapted(AbstractFetcherThread.scala:324)
        at kafka.utils.Implicits$MapExtensionMethods$.$anonfun$forKeyValue$1(Implicits.scala:62)
        at scala.collection.MapOps.foreachEntry(Map.scala:244)
        at scala.collection.MapOps.foreachEntry$(Map.scala:240)
        at scala.collection.AbstractMap.foreachEntry(Map.scala:405)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:324)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:124)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:123)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:123)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:106)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-12-21 15:46:02,842] WARN [ReplicaAlterLogDirsThread-2]: Partition topicB-86 marked as failed (kafka.server.ReplicaAlterLogDirsThread)
[2022-12-21 15:46:03,039] INFO [ReplicaAlterLogDirsThread-2]: Shutting down (kafka.server.ReplicaAlterLogDirsThread)
[2022-12-21 15:46:03,039] INFO [ReplicaAlterLogDirsThread-2]: Stopped (kafka.server.ReplicaAlterLogDirsThread)
[2022-12-21 15:46:03,039] INFO [ReplicaAlterLogDirsThread-2]: Shutdown completed (kafka.server.ReplicaAlterLogDirsThread)
```

完整的 log: [failure.txt](https://github.com/skiptests/astraea/files/10279442/failure.txt)

**Comment by chia7712** [comment]
可否看一下 https://issues.apache.org/jira/browse/KAFKA-9087 ? 那篇有描述另一種製造此錯誤的方式，看看是否一樣？

**Comment by garyparrot** [comment]
> 那篇有描述另一種製造此錯誤的方式，看看是否一樣？

他是用腳本做 data dir 的搬移，我想背後的原理差不多。他的敘述有提到似乎是 leader change 造成的，我剛剛檢查了一下，該 partition 的第一次搬移應該不會觸發 leader change，或許不是這個問題。

有問題的 partition 的 before/after

```json
      {
        "after": [
          {
            "brokerId": 0,
            "directory": "/tmp/log-folder-2"
          },
          {
            "brokerId": 3,
            "directory": "/tmp/log-folder-1"
          }
        ],
        "before": [
          {
            "brokerId": 0,
            "directory": "/tmp/log-folder-1",
            "size": 464324485
          },
          {
            "brokerId": 3,
            "directory": "/tmp/log-folder-0",
            "size": 464343997
          }
        ],
        "partition": 86,
        "topic": "topicB"
      },
```

**Comment by garyparrot** [comment]
我剛剛看了一下其他 broker 的 log 和原本產生的 Plan， 147 個負載平衡操作裡面只有這個 partition 出現這個問題，這個或許是很罕見的事件。

**Comment by chia7712** [comment]
> 我剛剛看了一下其他 broker 的 log 和原本產生的 Plan， 147 個負載平衡操作裡面只有這個 partition 出現這個問題，這個或許是很罕見的事件。

kafka alter 的邏輯有蠻多問題的，我之前有修過好幾個同步相關的bugs，我們可以先遺留著這個議題就好

**Comment by chia7712** [comment]
我覺得另一個議題是要否把有“future"這件事情加入“禁止”，也就是執行負載平衡時要避免遇到叢集有"future log"，這有兩個理由，第一個是這個bug，第二個則是負載平衡要決定策略時應該是在叢集中沒有任何“正在移動中”的partitions時才進行

**Comment by garyparrot** [comment]
> 我覺得另一個議題是要否把有“future"這件事情加入“禁止”，也就是執行負載平衡時要避免遇到叢集有"future log"，這有兩個理由，第一個是這個bug，第二個則是負載平衡要決定策略時應該是在叢集中沒有任何“正在移動中”的partitions時才進行

這些規則在執行計畫前有做檢查，不過搜尋計畫時忘了檢查，之後會給搜尋計畫加上這個檢查

**Comment by garyparrot** [comment]
呃，所以 Balancer 現在要暫時避免做 Data Directory 的搬移嗎，Balancer 做大量搬移的時候蠻容易撞到這個問題的，一旦撞到之後該叢集就再也不能做負載平衡，因為有些 replica 永遠都是 future 被檢查擋下

**Comment by chia7712** [comment]
> Balancer 做大量搬移的時候蠻容易撞到這個問題的，一旦撞到之後該叢集就再也不能做負載平衡，因為有些 replica 永遠都是 future 被檢查擋下

有機會試著寫寫看重現步驟嗎？我還沒時間去仔細看原因

不過你說的應該是目前的解法，可以先把該動作先註解掉並且寫上原因（附上此議題的連結)

**Comment by garyparrot** [comment]
> 有機會試著寫寫看重現步驟嗎？我還沒時間去仔細看原因

1. 建立 topic, partition 1000, replica 2, 數量多比較容易觸發

```
curl -X POST --location "http://localhost:8001/topics" \
    -H "Content-Type: application/json" \
    -d "{
          \"topics\": [
            {
              \"name\": \"topicA\",
              \"partitions\": 500,
              \"replicas\": 2
            },
            {
              \"name\": \"topicB\",
              \"partitions\": 500,
              \"replicas\": 2
            }
          ]
        }"
```

2. 開 Performance Tool

```
./gradlew run --args="performance --bootstrap.servers 192.168.103.177:25655,192.168.103.178:25655,192.168.103.179:25655,192.168.103.180:25655,192.168.103.181:25655 --topics topicA --run.until 3h --producers 8 --consumers 16 --key.size 10KiB --key.distribution zipfian --throughput 200MB/s"
```

```
./gradlew run --args="performance --bootstrap.servers 192.168.103.177:25655,192.168.103.178:25655,192.168.103.179:25655,192.168.103.180:25655,192.168.103.181:25655 --topics topicB --run.until 3h --producers 8 --consumers 16 --key.size 10KiB --key.distribution zipfian --throughput 400MB/s"
```

3. 讓 Performance Tool 跑 3 分鐘以上
4. 執行下面的 curl 來計算計劃

```
curl -X POST --location "http://localhost:8001/balancer" \
    -H "Content-Type: application/json" \
    -d "{
          \"timeout\": \"30s\",
          \"balancer\": \"org.astraea.common.balancer.algorithms.GreedyBalancer\",
          \"balancerConfig\": {
            \"shuffle.tweaker.min.step\": \"1\",
            \"shuffle.tweaker.max.step\": \"5\"
          },
          \"costWeights\": [
            { \"cost\": \"org.astraea.common.cost.NetworkIngressCost\", \"weight\": 1 },
            { \"cost\": \"org.astraea.common.cost.NetworkEgressCost\", \"weight\": 1 }
          ]
        }"
```

5. 算出計劃後執行

```
curl -X PUT --location "http://localhost:8001/balancer" \
    -H "Content-Type: application/json" \
    -d "{
          \"id\": \"計劃的編號\"
        }"
```

6. 等計劃執行完成
7. 再嘗試產生一次計劃

```
curl -X POST --location "http://localhost:8001/balancer" \
    -H "Content-Type: application/json" \
    -d "{
          \"timeout\": \"30s\",
          \"balancer\": \"org.astraea.common.balancer.algorithms.GreedyBalancer\",
          \"balancerConfig\": {
            \"shuffle.tweaker.min.step\": \"1\",
            \"shuffle.tweaker.max.step\": \"5\"
          },
          \"costWeights\": [
            { \"cost\": \"org.astraea.common.cost.NetworkIngressCost\", \"weight\": 1 },
            { \"cost\": \"org.astraea.common.cost.NetworkEgressCost\", \"weight\": 1 }
          ]
        }"
```

會出現下面的錯誤

```
java.lang.IllegalStateException: Another rebalance task might be working on. The following topic/partition has ongoing migration: [2-topicA-459, 1-topicB-305, 0-topicA-394, 1-topicA-423, 4-topicA-185, 3-topicB-483, 0-topicB-267, 4-topicB-290, 2-topicB-268]
```

看有問題的節點的 log，會有類似下面的錯誤訊息

```
[2022-12-29 15:05:52,050] ERROR [ReplicaAlterLogDirsThread-1]: Unexpected error occurred while processing data for partition topicB-483 at offset 21073 (kafka.server.ReplicaAlterLogDirsThread)
java.lang.IllegalStateException: Offset mismatch for the future replica topicB-483: fetched offset = 21073, log end offset = 0.
        at kafka.server.ReplicaAlterLogDirsThread.processPartitionData(ReplicaAlterLogDirsThread.scala:67)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$7(AbstractFetcherThread.scala:336)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6(AbstractFetcherThread.scala:325)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6$adapted(AbstractFetcherThread.scala:324)
        at kafka.utils.Implicits$MapExtensionMethods$.$anonfun$forKeyValue$1(Implicits.scala:62)
        at scala.collection.MapOps.foreachEntry(Map.scala:244)
        at scala.collection.MapOps.foreachEntry$(Map.scala:240)
        at scala.collection.AbstractMap.foreachEntry(Map.scala:405)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:324)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:124)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:123)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:123)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:106)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```

**Comment by chia7712** [comment]
@garyparrot 感謝提供資訊，這應該算是一個蠻嚴重的 kafka bug，不過可能同節點身上有異質硬碟目前還不常見，data folder 之間大量搬移不常出現所以這個 bugs 一直沒被處理 QQ

這個就先到這邊，我找時間跟Kafka 社群上討論一下

**Comment by chia7712** [comment]
@garyparrot 我推了一個最新版的 Kafka image `ghcr.io/skiptests/astraea/broker:trunk` 可否有機會試試看還會不會出現上述的錯誤？如果發生的話可否再把錯誤訊息貼上來？

**Comment by garyparrot** [comment]
我今天又花了一些時間研究這個題目，因為這和我的某個前進方向有關，如果沒法做到如data dir 的移動那條方向基本上就沒了👀。

我發現透過定義 preferred data dir 再做移動的方式，可以大幅下降出現這個問題的機率和次數（對比目前 straight plan executor 沒有 preferred 宣告硬搬移的做法）

不過大幅下降沒有把這個 future 問題的次數降到0，偶爾還是會發生，但發生時有點規律在裡面

1. 首先在 preferred 做法下出錯的 replica 都是屬於 folder to folder 的移動（此 partition 已經在同個節點，只是換硬碟），沒看到 broker to broker 的移動有問題。
2. 我目前觀察到所有出問題的 replica，他們都是原本是 leader，但是被轉成 follower 且換 directory。我目前還沒看到反例，這也許是只是巧合，剛好出錯的 5 個 replica 都是這種搬移模式，我嘗試寫測試重現這個搬移情境但是沒有錯誤發生，不知道是不是缺了什麼條件沒觸法到。 btw 我記得上面的 JIRA 討論有人有提到 leadership 和這個錯誤有關，不知道有沒有關聯。

上面是我目前的發現

**Comment by garyparrot** [comment]
> 我推了一個最新版的 Kafka image ghcr.io/skiptests/astraea/broker:trunk 可否有機會試試看還會不會出現上述的錯誤？如果發生的話可否再把錯誤訊息貼上來？

了解，晚點會試試看

**Comment by garyparrot** [comment]
然後上面的發現和那個版本的 Kafka 無關，是我幾個小時前測試的

**Comment by chia7712** [comment]
> 首先在 preferred 做法下出錯的 replica 都是屬於 folder to folder 的移動（此 partition 已經在同個節點，只是換硬碟）

現在最好的做法就是先把這個功能遮掉，就算修好了也只能用於最新的 kafka （大概又是一個要寫在 QA 文件中的點）

> 因為這和我的某個前進方向有關，如果沒法做到如data dir 的移動那條方向基本上就沒了

哪個方向？可以多講一些嗎

**Comment by garyparrot** [comment]
> 哪個方向？可以多講一些嗎

確保 data dir 不會放到超出上限而 offline 的 cost function, 這個實作需要能了解 retention 設定和 partition 資料增長速度的關聯

其實我目前有三個方向，這個方向斷了我還能網其他地方繼續做，所以其實也還好

**Comment by chia7712** [comment]
> 確保 data dir 不會放到超出上限而 offline 的 cost function,

這是指硬碟容量放不放得下嗎？

**Comment by garyparrot** [comment]
> 這是指硬碟容量放不放得下嗎？

差不多，但可能還有點未來能不能放得下的味道在

**Comment by chia7712** [comment]
> 差不多，但可能還有點未來能不能放得下的味道在

是否能先把這個想法開一個議題稍微講一下，並且提出為何現在不能做（上述的bugs）

**Comment by garyparrot** [comment]
>> 我推了一個最新版的 Kafka image ghcr.io/skiptests/astraea/broker:trunk 可否有機會試試看還會不會出現上述的錯誤？如果發生的話可否再把錯誤訊息貼上來？
>>
> 了解，晚點會試試看

我剛剛測試了一下，還是會有錯誤出現

```
[2023-01-02 05:20:39,962] ERROR [ReplicaAlterLogDirsThread-1]: Unexpected error occurred while processing data for partition topicB-141 at offset 53466 (kafka.server.ReplicaAlterLogDirsThread)
java.lang.IllegalStateException: Offset mismatch for the future replica topicB-141: fetched offset = 53466, log end offset = 0.
        at kafka.server.ReplicaAlterLogDirsThread.processPartitionData(ReplicaAlterLogDirsThread.scala:67)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$7(AbstractFetcherThread.scala:353)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6(AbstractFetcherThread.scala:342)
        at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6$adapted(AbstractFetcherThread.scala:341)
        at kafka.utils.Implicits$MapExtensionMethods$.$anonfun$forKeyValue$1(Implicits.scala:62)
        at scala.collection.MapOps.foreachEntry(Map.scala:244)
        at scala.collection.MapOps.foreachEntry$(Map.scala:240)
        at scala.collection.AbstractMap.foreachEntry(Map.scala:405)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:341)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:140)
        at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:139)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:139)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:122)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```

Full log: [error-01-02.txt](https://github.com/skiptests/astraea/files/10330114/error-01-02.txt)

建立 topic 的 cURL

```
curl -X POST --location "http://localhost:8001/topics" \
    -H "Content-Type: application/json" \
    -d "{
          \"topics\": [
            {
              \"name\": \"topicA\",
              \"partitions\": 300,
              \"replicas\": 3
            },
            {
              \"name\": \"topicB\",
              \"partitions\": 300,
              \"replicas\": 3
            }
          ]
        }"
```

產生計劃的 cURL

```
curl -X POST --location "http://localhost:8001/balancer" \
    -H "Content-Type: application/json" \
    -d "{
          \"timeout\": \"180s\",
          \"balancer\": \"org.astraea.common.balancer.algorithms.GreedyBalancer\",
          \"balancerConfig\": {
            \"shuffle.tweaker.min.step\": \"1\",
            \"shuffle.tweaker.max.step\": \"5\"
          },
          \"costWeights\": [
            { \"cost\": \"org.astraea.common.cost.NetworkIngressCost\", \"weight\": 1 },
            { \"cost\": \"org.astraea.common.cost.NetworkEgressCost\", \"weight\": 5 }
          ]
        }"
```

**Comment by garyparrot** [comment]
>> 差不多，但可能還有點未來能不能放得下的味道在
>> 
> 是否能先把這個想法開一個議題稍微講一下，並且提出為何現在不能做（上述的bugs）

see #1393

**Comment by chia7712** [comment]
@garyparrot 感謝！

**Comment by chia7712** [comment]
此議題已經在 https://github.com/apache/kafka/pull/13075 處理完成
