### ISSUE TITLE
Exporter:Tolerance exceeded in error handler

### ISSUE THREAD

**Issue by Haser0305** [skiptests/astraea#1375]
現行connector 在寫出檔案時會出錯，報錯內容如下
```
2022-12-30T17:06:14.456723975Z org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
2022-12-30T17:06:14.456728580Z 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:223)
2022-12-30T17:06:14.456732054Z 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:149)
2022-12-30T17:06:14.456735051Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:513)
2022-12-30T17:06:14.456738288Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
2022-12-30T17:06:14.456741173Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
2022-12-30T17:06:14.456744044Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
2022-12-30T17:06:14.456746877Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
2022-12-30T17:06:14.456749851Z 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
2022-12-30T17:06:14.456752669Z 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
2022-12-30T17:06:14.456755474Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-12-30T17:06:14.456758343Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-12-30T17:06:14.456762014Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-12-30T17:06:14.456765184Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-12-30T17:06:14.456768220Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-12-30T17:06:14.456771235Z Caused by: org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error: 
2022-12-30T17:06:14.456774288Z 	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:324)
2022-12-30T17:06:14.456777165Z 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:88)
2022-12-30T17:06:14.456780064Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$3(WorkerSinkTask.java:513)
2022-12-30T17:06:14.456794656Z 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)
2022-12-30T17:06:14.456799013Z 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)
2022-12-30T17:06:14.456802176Z 	... 13 more
2022-12-30T17:06:14.456805074Z Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
2022-12-30T17:06:14.456808267Z  at [Source: (byte[])"test"; line: 1, column: 5]
2022-12-30T17:06:14.456811158Z 	at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:66)
2022-12-30T17:06:14.456813966Z 	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:322)
2022-12-30T17:06:14.456816809Z 	... 17 more
2022-12-30T17:06:14.456819564Z Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
2022-12-30T17:06:14.456822840Z  at [Source: (byte[])"test"; line: 1, column: 5]
2022-12-30T17:06:14.456825819Z 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
2022-12-30T17:06:14.456828777Z 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
2022-12-30T17:06:14.456831794Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3635)
2022-12-30T17:06:14.456835216Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3608)
2022-12-30T17:06:14.456838061Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchToken2(UTF8StreamJsonParser.java:2949)
2022-12-30T17:06:14.456840894Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchTrue(UTF8StreamJsonParser.java:2883)
2022-12-30T17:06:14.456843754Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:875)
2022-12-30T17:06:14.456846840Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:794)
2022-12-30T17:06:14.456849802Z 	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703)
2022-12-30T17:06:14.456852722Z 	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3090)
2022-12-30T17:06:14.456855633Z 	at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:64)
2022-12-30T17:06:14.456858473Z 	... 18 more
2022-12-30T17:06:14.457431925Z 
```

**Comment by chia7712** [comment]
> 現行connector 在寫出檔案時會出錯，報錯內容如下

應該是 json serializer 轉換出的問題，如果是用 gui 的話，可否將 converter 的欄位都用`org.apache.kafka.connect.converters.ByteArrayConverter`後再跑跑看

**Comment by Haser0305** [comment]
在gui創建時設定後就沒有出現問題，看來應該就是這個原因了

**Comment by chia7712** [comment]
> 在gui創建時設定後就沒有出現問題，看來應該就是這個原因了

這個算是一個 kafka 的小陷阱，可否幫忙在 backup 工具中提起？也就是 kafka worker "預設"會用 json 格式來拆 records，但對於 topic 內的資料並非來自 connector json 封裝時，拆包裹的時候就會出問題，此時要設定 converter 改成 byte array converter 才能順利解析資料

**Comment by Haser0305** [comment]
> 這個算是一個 kafka 的小陷阱，可否幫忙在 backup 工具中提起？也就是 kafka worker "預設"會用 json 格式來拆 records，但對於 topic 內的資料並非來自 connector json 封裝時，拆包裹的時候就會出問題，此時要設定 converter 改成 byte array converter 才能順利解析資料

好的，那我在gui doc 與 connector.exporter 那邊在補充說明這部份的事情
