### ISSUE TITLE
`LogMetrics.Log` MBean disappear from Kafka MBeanServer in rare case

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1388]
剛剛測試時遇到一個罕見的狀況，在經過多次密集頻繁的搬移後，計劃突然怎麼樣都沒辦法生成，檢查後發現這個錯誤：

```
org.astraea.common.cost.NoSufficientMetricsException: Not enough metrics for org.astraea.common.cost.NetworkIngressCost: Initial clusterInfo required, the following replicas are mismatch: [1-topicB-350]
	at org.astraea.common.cost.NetworkCost.fail(NetworkCost.java:229)
	at org.astraea.common.cost.NetworkCost.updateCurrentCluster(NetworkCost.java:97)
	at org.astraea.common.cost.NetworkCost.clusterCost(NetworkCost.java:103)
	at org.astraea.common.cost.HasClusterCost$1.lambda$clusterCost$0(HasClusterCost.java:53)
	at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:248)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:541)
```

錯誤表示 `topicB-350-1` 這個 replica 的 `LogMetrics.Log.Size` 沒有撈取到，我確認 `Admin#ClusterInfo` 的回傳結果，該 partition 確實是服務在節點 1，且看起來沒有 future 或是 adding/removing 的標記在上面，去查節點 1 的 log 沒有看到特別明顯的錯誤。

透過 VisualVM 連進去該節點的 MBeanServer 後，發現 Partition 350 真的沒有對應的 `kafka.log:type=Log,name=Size,topic=topicB,partition=350` Mbean。

後來對該 Kafka 的 docker container 做 restart 後，這個 Partition 350 的 `kafka.log:type=Log,name=Size,topic=topicB,partition=350` 的 MBean 就出現了，看起來是 Kafka 內部效能指標的處理問題，這個 MBean 似乎有消失的可能。但重開節點可以解決。

**Comment by chia7712** [comment]
這是一個已知的 Kafka bug ，我已經修復了 (see https://github.com/apache/kafka/commit/13d1c086f39531e2a47fe8475c4fd79e300adabd)

目前沒有任何 workaround 可以處理這個狀況，唯一的手法就像你說的重開機 ...

或許我們可以在balancer 文件中提一下這件事情，你覺得呢？

**Comment by garyparrot** [comment]
> 或許我們可以在balancer 文件中提一下這件事情，你覺得呢？

聽起來不錯，可以加開一個 troubleshooting section

**Comment by chia7712** [comment]
> 可以加開一個 troubleshooting section

喔 我喜歡這個標題！

**Comment by chia7712** [comment]
我把這個議題加入 0.2.0 release 中，希望我們能有一個頁面來描述這些奇形怪狀
