### ISSUE TITLE
BeanCollectorTest 有時會出錯

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#142]
部份錯誤訊息如下：
```
BeanCollectorTest > testAddNode() FAILED
    org.opentest4j.AssertionFailedError: expected: not equal but was: <0> 
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at app//org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:276)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:96)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:88)
        at app//org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:1977)
        at app//org.astraea.metrics.BeanCollectorTest.lambda$testAddNode$22(BeanCollectorTest.java:181)
        at java.base@11.0.11/java.util.ArrayList.forEach(ArrayList.java:1541)
        at app//org.astraea.metrics.BeanCollectorTest.testAddNode(BeanCollectorTest.java:179)
```

**Comment by chia7712** [comment]
@chinghongfang 你有打算修嗎？還是我來？

**Comment by chinghongfang** [comment]
這個想交由學長來修。
感謝。

**Comment by chia7712** [comment]
> 這個想交由學長來修。

下次可以直接把議題指定給我
