### ISSUE TITLE
Fix flaky ExporterTest#testFtpSinkTaskIntervalWith2Writers

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1432]
```
ExporterTest > testFtpSinkTaskIntervalWith2Writers() FAILED
[4359](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4360)
    org.opentest4j.AssertionFailedError: expected: <2> but was: <1>
[4360](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4361)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
[4361](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4362)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
[4362](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4363)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
[4363](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4364)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
[4364](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4365)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
[4365](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4366)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
[4366](https://github.com/skiptests/astraea/actions/runs/3921392753/jobs/6703669539#step:5:4367)
        at app//org.astraea.connector.backup.ExporterTest.testFtpSinkTaskIntervalWith2Writers(ExporterTest.java:394)
```

**Comment by chia7712** [comment]
@Haser0305 Could you please take a look?
