### ISSUE TITLE
[PERF] Confusing exception raised when any send targets are offline

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1575]
Performance Tool 在啟動的時候會將 Consumer Groups 的 Offset 調整到目標 Partition 的最新 Offset，該 Offset 的值源自 `Admin#latestOffsets` 函數，而該函數的實作會在 Partition offline 的時候回報他的 offset 是 `-1`，在這個情形下，Performance Tool 嘗試將 Consumer Group 的 Offset 調整成 -1，進而觸發下面很混淆的錯誤訊息。

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: seek offset must not be a negative number
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalArgumentException: seek offset must not be a negative number
	at org.apache.kafka.clients.consumer.KafkaConsumer.seek(KafkaConsumer.java:1591)
	at org.astraea.common.consumer.SeekStrategy.lambda$static$7(SeekStrategy.java:61)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.astraea.common.consumer.SeekStrategy.lambda$static$8(SeekStrategy.java:61)
	at org.astraea.common.consumer.SeekStrategy.apply(SeekStrategy.java:89)
	at org.astraea.common.consumer.TopicsBuilder.lambda$build$3(TopicsBuilder.java:132)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 6 more
```

這個錯誤訊息可能會讓人無法理解發生了什麼事情，可能需要做一些修正

* `Performance Tool` 在遇到這個情況的時候要提供比較友善直覺的錯誤訊息。
* `Admin#earliestOffsets` 和 `Admin#latestsOffsets` 的 Javadoc 應該要提及這件 `-1` 的 case。

**Comment by chia7712** [comment]
有道理！

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 有機會試試看嗎？

**Comment by Haser0305** [comment]
> @Haser0305 @chaohengstudent 有機會試試看嗎？

好的，最近找一個時間處理這個
