### ISSUE TITLE
fix BalancerHandlerTest#testMoveCost

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1597]
```
BalancerHandlerTest > testMoveCost(String, String) > org.astraea.app.web.BalancerHandlerTest.testMoveCost(String, String)[2] FAILED
[855](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:856)
    org.opentest4j.AssertionFailedError: expected: <4> but was: <3>
[856](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:857)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
[857](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:858)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
[858](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:859)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
[859](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:860)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
[860](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:861)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
[861](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:862)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
[862](https://github.com/skiptests/astraea/actions/runs/4501570821/jobs/7922186000?pr=1596#step:5:863)
        at app//org.astraea.app.web.BalancerHandlerTest.testMoveCost(BalancerHandlerTest.java:360)
```

**Comment by chia7712** [comment]
it should be fixed by #1584
