### ISSUE TITLE
[TEST] fix flaky `AssignorTest#testAddNode()`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1609]
https://github.com/skiptests/astraea/actions/runs/4530981188/jobs/7980572870#step:5:2021

```
AssignorTest > testAddNode() FAILED
    org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at app//org.astraea.common.assignor.AssignorTest.testAddNode(AssignorTest.java:166)
```

**Comment by harryteng9527** [comment]
@chia7712 沒問題
