### ISSUE TITLE
fix BalancerHandlerTest#testRebalanceDetectOngoing

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1613]
```
BalancerHandlerTest > testRebalanceDetectOngoing() FAILED
[945](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:946)
    java.util.concurrent.TimeoutException: testRebalanceDetectOngoing() timed out after 60 seconds
[946](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:947)
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
[947](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:948)
        at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
[948](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:949)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
[949](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:950)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
[950](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:951)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
[951](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:952)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
[952](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:953)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
[953](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:954)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
[954](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:955)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
[955](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:956)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
[956](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:957)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
[957](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:958)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
[958](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:959)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
[959](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:960)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
[960](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:961)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[961](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:962)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
[962](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:963)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
[963](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:964)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
[964](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:965)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[965](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:966)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[966](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:967)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[967](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:968)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[968](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:969)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[969](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:970)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[970](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:971)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[971](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:972)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[972](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:973)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[973](https://github.com/skiptests/astraea/actions/runs/4535113243/jobs/7990151134?pr=1612#step:5:974)
        at
```

**Comment by chia7712** [comment]
@garyparrot 你覺得 #1616 是否修復了這個議題？

**Comment by chia7712** [comment]
ok，感謝告知，那我來看一下
