### ISSUE TITLE
Fix flaky BalancerNodeTest#testGenerator

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1695]
```
BalancerNodeTest > testGenerator() FAILED
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
        at app//org.astraea.gui.tab.health.BalancerNodeTest.testGenerator(BalancerNodeTest.java:99)
```

**Comment by chia7712** [comment]
@qoo332001 #1688 是否有修正此錯誤了？

**Comment by qoo332001** [comment]
> @qoo332001 https://github.com/skiptests/astraea/pull/1688 是否有修正此錯誤了？

https://github.com/skiptests/astraea/pull/1688 修正的錯誤與這個錯誤應該沒有關係，另外我在本地跑了很多次都沒辦法重現這個錯誤，所以也不確定應該這麼修這個錯誤...

**Comment by chia7712** [comment]
@qoo332001 感謝確認，如果確定無法重現的話就可以關閉了
