### ISSUE TITLE
Fix flaky BalancerHandlerTest#testReport

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1701]
```
BalancerHandlerTest > testReport() FAILED
    org.opentest4j.AssertionFailedError: expected: not equal but was: <0>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:277)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:263)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:258)
        at app//org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:2128)
        at app//org.astraea.app.web.BalancerHandlerTest.lambda$testReport$6(BalancerHandlerTest.java:170)
        at java.base@17.0.6/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at app//org.astraea.app.web.BalancerHandlerTest.testReport(BalancerHandlerTest.java:170)
```

**Comment by chia7712** [comment]
@qoo332001 #1688 的修補跟這個有關嗎？可否看一下
