### ISSUE TITLE
[TEST] Fix flaky `AssignorTest#testAddNode()` and `AssignorTest#testUnregisterId()`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1714]
https://github.com/skiptests/astraea/actions/runs/4927007925/jobs/8803363392#step:5:2071

```
AssignorTest > testAddNode() FAILED
    org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at app//org.astraea.common.assignor.AssignorTest.testAddNode(AssignorTest.java:171)
```

https://github.com/skiptests/astraea/actions/runs/4927007925/jobs/8803363392#step:5:2095

```
AssignorTest > testUnregisterId() FAILED
    org.opentest4j.AssertionFailedError: expected: <2> but was: <3>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at app//org.astraea.common.assignor.AssignorTest.testUnregisterId(AssignorTest.java:148)
```

**Comment by chia7712** [comment]
@harryteng9527 Could you please take a look ?

**Comment by harryteng9527** [comment]
已經在 https://github.com/skiptests/astraea/pull/1712#issue-1702157057 移除，因為已經用不到 `checkUnregister` 了

**Comment by chia7712** [comment]
@harryteng9527 thanks for response. please close this issue if it has been fixed.
