### ISSUE TITLE
[TEST] Fix flaky `RecordGeneratorTest#testDistributedValueSize()`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1771]
```
RecordGeneratorTest > testDistributedValueSize() FAILED
    org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:228)
        at app//org.astraea.common.producer.RecordGeneratorTest.testDistributedValueSize(RecordGeneratorTest.java:153)
```

https://github.com/skiptests/astraea/actions/runs/5058162836/jobs/9077895348#step:5:4448

**Comment by chia7712** [comment]
close as duplicate to #1827
