### ISSUE TITLE
在performance結束後offset tool鏈接超時無法顯示資訊

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#245]
![Screenshot from 2022-02-20 23-34-37](https://user-images.githubusercontent.com/43372856/154850771-7c50ea98-367c-4e17-835e-c0fe796c21c0.png)
![Screenshot from 2022-02-20 23-33-08](https://user-images.githubusercontent.com/43372856/154850777-04c37aae-ac2d-477d-bedb-1d1f5fd3e888.png)

如圖，能夠通過kafka tool獲取topic name，但我無法用offset獲取分布，它會顯示超時。在performance中是可以獲取到分布的，上述情況爲performance結束後。
可能還需要確認一下上述情況是否必會處罰該bug。

**Comment by garyparrot** [comment]
今天從學長那邊弄到一臺可以重現這個錯誤的叢集

初步追蹤後找到 exception 出現在這裏

https://github.com/skiptests/astraea/blob/7202f42b261cb5ab79950a9eda44cd167335757b/app/src/main/java/org/astraea/topic/Builder.java#L124-L152

看起來 Admin 在針對特定 Topic/Partitions 取得 offsets 時出現 request timeout 的問題。

後面用 Kafka 自帶的工具測試了一下:
```
./kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list server:13843 --topic testPerformance-1645628445149 --time -2
```

結果
```
Error: topic-partition testPerformance-1645628445149:11 does not have a leader. Skip getting offsets
Error: topic-partition testPerformance-1645628445149:27 does not have a leader. Skip getting offsets
Error: topic-partition testPerformance-1645628445149:15 does not have a leader. Skip getting offsets
Error: topic-partition testPerformance-1645628445149:3 does not have a leader. Skip getting offsets
Error: topic-partition testPerformance-1645628445149:19 does not have a leader. Skip getting offsets
Error: topic-partition testPerformance-1645628445149:7 does not have a leader. Skip getting offsets
testPerformance-1645628445149:0:0
testPerformance-1645628445149:1:0
testPerformance-1645628445149:2:0
testPerformance-1645628445149:4:0
testPerformance-1645628445149:5:0
testPerformance-1645628445149:6:0
testPerformance-1645628445149:8:0
testPerformance-1645628445149:9:0
testPerformance-1645628445149:10:0
testPerformance-1645628445149:12:0
testPerformance-1645628445149:13:0
testPerformance-1645628445149:14:0
testPerformance-1645628445149:16:0
testPerformance-1645628445149:17:0
testPerformance-1645628445149:18:0
testPerformance-1645628445149:20:0
testPerformance-1645628445149:21:0
testPerformance-1645628445149:22:0
testPerformance-1645628445149:23:0
testPerformance-1645628445149:24:0
testPerformance-1645628445149:25:0
testPerformance-1645628445149:26:0
testPerformance-1645628445149:28:0
testPerformance-1645628445149:29:0
testPerformance-1645628445149:30:0
testPerformance-1645628445149:31:0
testPerformance-1645628445149:32:0
testPerformance-1645628445149:33:0
testPerformance-1645628445149:34:0
testPerformance-1645628445149:35:0
testPerformance-1645628445149:36:0
testPerformance-1645628445149:37:0
testPerformance-1645628445149:38:0
testPerformance-1645628445149:39:0
testPerformance-1645628445149:40:0
testPerformance-1645628445149:41:0
testPerformance-1645628445149:42:0
testPerformance-1645628445149:43:0
testPerformance-1645628445149:44:0
testPerformance-1645628445149:45:0
testPerformance-1645628445149:46:0
testPerformance-1645628445149:47:0
testPerformance-1645628445149:48:0
testPerformance-1645628445149:49:0
```

我仔細看了一下

https://github.com/apache/kafka/blob/99b9b3e84f4e98c3f07714e1de6a139a004cbc5b/core/src/main/scala/kafka/tools/GetOffsetShell.scala#L126-L152

Apache Kafka 他們建立了一個 Consumer 來撈取 offset WTF

後面會繼續追蹤

**Comment by garyparrot** [comment]
@wycccccc 

我可能找到原因了, 這是那個叢集中有問題的 Topic 的狀態

```
Topic: testPerformance-1645628445149	TopicId: kI082taWRpiG9Iwn83QDew	PartitionCount: 50	ReplicationFactor: 1	Configs: 
	Topic: testPerformance-1645628445149	Partition: 0	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 1	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 2	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 3	Leader: none	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 4	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 5	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 6	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 7	Leader: none	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 8	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 9	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 10	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 11	Leader: none	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 12	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 13	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 14	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 15	Leader: none	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 16	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 17	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 18	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 19	Leader: none	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 20	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 21	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 22	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 23	Leader: 1004	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 24	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 25	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 26	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 27	Leader: none	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 28	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 29	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 30	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 31	Leader: 1004	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 32	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 33	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 34	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 35	Leader: 1004	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 36	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 37	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 38	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 39	Leader: 1004	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 40	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 41	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 42	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 43	Leader: 1004	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 44	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 45	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: testPerformance-1645628445149	Partition: 46	Leader: 1003	Replicas: 1003	Isr: 1003
	Topic: testPerformance-1645628445149	Partition: 47	Leader: 1004	Replicas: 1004	Isr: 1004
	Topic: testPerformance-1645628445149	Partition: 48	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: testPerformance-1645628445149	Partition: 49	Leader: 1001	Replicas: 1001	Isr: 1001
```

注意到有些 Partition 的 Leader 是 none，然後看起來他們大多數都位在 Broker id = 1004 那臺

我剛剛去看過 1004 的 log

```
[2022-02-24 03:20:46,051] WARN [ReplicaManager broker=1004] Unable to describe replica dirs for /tmp/log-folder-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Log directory /tmp/log-folder-0 is offline
[2022-02-24 03:28:57,459] WARN [ReplicaManager broker=1004] Unable to describe replica dirs for /tmp/log-folder-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Log directory /tmp/log-folder-0 is offline
[2022-02-24 06:30:48,940] WARN [ReplicaManager broker=1004] Unable to describe replica dirs for /tmp/log-folder-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Log directory /tmp/log-folder-0 is offline
[2022-02-24 06:46:59,501] WARN [ReplicaManager broker=1004] Unable to describe replica dirs for /tmp/log-folder-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Log directory /tmp/log-folder-0 is offline
[2022-02-24 06:47:28,387] WARN [ReplicaManager broker=1004] Unable to describe replica dirs for /tmp/log-folder-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Log directory /tmp/log-folder-0 is offline
[2022-02-24 06:47:37,631] WARN [ReplicaManager broker=1004] Unable to describe replica dirs for /tmp/log-folder-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Log directory /tmp/log-folder-0 is offline
```

每次執行 `offset` 工具，他都會噴出下面這個 Warning。看起來那個 log-folder 沒了，所以 Kafka 目標 topic/partition 的 offset 是多少他不知道，他 Broker RPC Response 直到 timeout 都回不來，應該是在等這個 log folder 上線，拿到確切的 offset 後回應 Admin Client。

我會再確認一下，如果確定是這個問題我再看要怎麼補進他。

謝謝

**Comment by garyparrot** [comment]
套用下面這些修改

```diff
diff --git a/app/src/test/java/org/astraea/service/BrokerCluster.java b/app/src/test/java/org/astraea/service/BrokerCluster.java
index 338f69c..02c44e3 100644
--- a/app/src/test/java/org/astraea/service/BrokerCluster.java
+++ b/app/src/test/java/org/astraea/service/BrokerCluster.java
@@ -1,5 +1,8 @@
 package org.astraea.service;
 
+import kafka.server.KafkaServer;
+
+import java.util.List;
 import java.util.Map;
 import java.util.Set;
 
@@ -10,4 +13,6 @@ public interface BrokerCluster extends AutoCloseable {
 
   /** @return the log folders used by each broker */
   Map<Integer, Set<String>> logFolders();
+
+  List<KafkaServer> servers();
 }
diff --git a/app/src/test/java/org/astraea/service/Services.java b/app/src/test/java/org/astraea/service/Services.java
index 1031d11..9336783 100644
--- a/app/src/test/java/org/astraea/service/Services.java
+++ b/app/src/test/java/org/astraea/service/Services.java
@@ -2,6 +2,7 @@ package org.astraea.service;
 
 import java.io.File;
 import java.net.InetSocketAddress;
+import java.util.List;
 import java.util.Map;
 import java.util.Properties;
 import java.util.Set;
@@ -92,6 +93,11 @@ public final class Services {
             .boxed()
             .collect(Collectors.toMap(Function.identity(), tempFolders::get));
       }
+
+        @Override
+        public List<KafkaServer> servers() {
+            return brokers;
+        }
     };
   }
```

然後執行下面這段程式可以重現這個問題

```java
package org.astraea.service;

import org.astraea.topic.TopicAdmin;
import org.astraea.topic.TopicExplorer;

import java.util.Set;

public class Ignore extends RequireBrokerCluster {

    public static void main(String[] args) throws Exception {

        final ZookeeperCluster zookeeperCluster = Services.zookeeperCluster();
        final BrokerCluster brokerCluster = Services.brokerCluster(zookeeperCluster, 3);
        final TopicAdmin admin = TopicAdmin.of(brokerCluster.bootstrapServers());

        String topicName = "Testing";
        int brokerId = 0;

        // Create topic
        admin.creator()
                .topic(topicName)
                .numberOfPartitions(1)
                .numberOfReplicas((short)1)
                .create();

        // Migrate everything to the same broker
        admin.migrator()
                .partition("Testing", 0)
                .moveTo(Set.of(brokerId));

        // Shutdown this broker
        brokerCluster.servers().get(brokerId).shutdown();

        // Execute TopicExplorer, now it supposed to raise a TimeoutException
        TopicExplorer.main(new String[]{
                "--bootstrap.servers", brokerCluster.bootstrapServers(),
                "--topics", topicName
        });
    }
}
```

**Comment by chia7712** [comment]
> 套用下面這些修改

@garyparrot 為何不直接發PR?

**Comment by garyparrot** [comment]
Patc還在煮

**Comment by garyparrot** [comment]
@chia7712 

如果用 `AdminClient#listOffsets` 取 offset，不管有沒有嘗試索取每 leader 的 partition，他都會等到所有 Topic 下的每個 partition 都有 leader 後才會回傳結果。
如果用 `Consumer#beginningOffsets` 取 offset 則沒有這些限制，只要指定 TopicPartition 中沒有包含沒 leader 的 partition, 結果就會直接回傳。

我現在要用 Consumer 改寫 fetch 的邏輯嗎，這樣會看起來很詭異，因為在 AdminClient 裡面混雜了 Consumer。
或是直接讓 TopicExplorer 檢查是否每個 partition 都有 leader, 沒有滿足條件就不執行。

**Comment by chia7712** [comment]
>  Consumer#beginningOffsets 

這個方法是舊時代的東西，除非必要否則盡可能避免

>  TopicExplorer 檢查是否每個 partition 都有 leader, 沒有滿足條件就不執行。

這個方法可以試試看，不過`leader`的選舉應該很快才對，在測試中是遭遇了什麼狀況？

**Comment by garyparrot** [comment]
> 不過leader的選舉應該很快才對，在測試中是遭遇了什麼狀況？

出問題的測試環境只有一個 replica, 然後那個 replica 所屬的 broker 壞了。整個叢集沒有其他備份可用所以 leader 選不出來

**Comment by chia7712** [comment]
> 出問題的測試環境只有一個 replica, 然後那個 replica 所屬的 broker 壞了。整個叢集沒有其他備份可用所以 leader 選不出來

所以當從集中該partition沒有配置到leader的時候，`AdminClient#listOffsets`會卡住嗎？如果是的話，可否把出現的錯誤資訊貼上來？謝謝

**Comment by garyparrot** [comment]
```
> Task :app:TopicExplorer.main()
[main] INFO org.apache.kafka.clients.admin.AdminClientConfig - AdminClientConfig values: 
	bootstrap.servers = [0.0.0.0:11262, 0.0.0.0:15548]
	client.dns.lookup = use_all_dns_ips
	client.id = 
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS

[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka version: 3.1.0
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka commitId: 37edeed0777bacb3
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1645804733539
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Node -2 disconnected.
[kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -2 (/127.0.0.1:15548) could not be established. Broker may not be available.
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-1 unregistered
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.common.metrics.Metrics - Metrics scheduler closed
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.common.metrics.Metrics - Metrics reporters closed
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: metadata
	at org.astraea.Utils.handleException(Utils.java:24)
	at org.astraea.topic.Builder$TopicAdminImpl.earliestOffset(Builder.java:131)
	at org.astraea.topic.Builder$TopicAdminImpl.offsets(Builder.java:213)
	at org.astraea.topic.TopicExplorer.execute(TopicExplorer.java:65)
	at org.astraea.topic.TopicExplorer.main(TopicExplorer.java:105)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: metadata
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: metadata

	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at org.astraea.topic.Builder$TopicAdminImpl.lambda$earliestOffset$17(Builder.java:138)
	at org.astraea.Utils.handleException(Utils.java:22)
	... 4 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: metadata
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: metadata


> Task :app:TopicExplorer.main() FAILED

Execution failed for task ':app:TopicExplorer.main()'.
> Process 'command '/usr/lib/jvm/java-16-jdk/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.



```
