### ISSUE TITLE
fix flaky NodeLoadClientTest.testLoadSituation

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#248]
```
NodeLoadClientTest > testLoadSituation() FAILED
[572](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:572)
    org.opentest4j.AssertionFailedError: expected: <5> but was: <10>
[573](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:573)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[574](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:574)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
[575](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:575)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
[576](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:576)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
[577](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:577)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:541)
[578](https://github.com/skiptests/astraea/runs/5290325567?check_suite_focus=true#step:5:578)
        at app//org.astraea.partitioner.nodeLoadMetric.NodeLoadClientTest.testLoadSituation(NodeLoadClientTest.java:106)
```

**Comment by chia7712** [comment]
`NodeLoadClientTest` is already removed by https://github.com/skiptests/astraea/commit/a1b1bb03dd9563210ca8ffab6ae5dcb1627672a2
