### ISSUE TITLE
Flaky ReplicaCollieTest

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#250]
有時候會出現這個錯誤。
```
ReplicaCollieTest > testBrokerMigrator() FAILED
    java.lang.IllegalArgumentException: ReplicaCollieTest is existent but its replicas: 3 is not equal to expected: 2
        at org.astraea.topic.Builder$CreatorImpl.lambda$create$1(Builder.java:365)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at org.astraea.topic.Builder$CreatorImpl.create(Builder.java:359)
        at org.astraea.topic.ReplicaCollieTest.testBrokerMigrator(ReplicaCollieTest.java:43)
```

**Comment by qoo332001** [comment]
因為我有兩個test 是使用相同的topice name `ReplicaCollieTest` 然後預設的`replicas`是2，因為在test中會有搬移的行為，所以有可能搬移後造成replica數變成3，之後下一格test再次要執行的時候就會發現`replica`數不等於2而跳出這個錯誤，所以我把兩個test的`topic name`改不一樣理論上就不會再跳這個錯了。

**Comment by chia7712** [comment]
> 所以我把兩個test的topic name改不一樣理論上就不會再跳這個錯了。

please file PR :)
