### ISSUE TITLE
Flaky MemoryCostTest#testCost

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#321]
```
MemoryCostTest > testCost() FAILED
    org.opentest4j.AssertionFailedError: expected: <0.53> but was: <0.52>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:894)
        at app//org.astraea.cost.brokersMetrics.MemoryCostTest.testCost(MemoryCostTest.java:84)
```

**Comment by chia7712** [comment]
@wycccccc 可以幫忙看一下嗎？我在容器內跑測試的時候這隻測試一定會失敗

**Comment by chia7712** [comment]
測試了一下，這個測試在最新版的JDK 11.0.15一定會失敗，其他版本則不會，搞不好是踩到JDK bug了

**Comment by wycccccc** [comment]
確實是一個很神奇的bug，我有在#315 把它修掉，應該是Math.round的底層相關內容這個JDK有改到什麼，改成其他不那麼敏感的數字就可以了。如果沒有特別的影響，等#315 meger問題就解決了。
