### ISSUE TITLE
完成第一個release

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#41]
這邊紀錄一下我們的第一次release，這個目的是為了讓大家可以在不用自己建置專案下也能使用這個專案的功能。

https://github.com/skiptests/astraea/releases/tag/0.0.1-alpha.3

希望能在10月做一個正式的release

**Comment by garyparrot** [comment]
感謝👍

在 Windows 和 Linux 上測試可以成功執行，不過 End2EndLatency 和 OffsetExplorer 在抱怨 SLF4J 沒有 Logger 實作

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by chia7712** [comment]
> 不過 End2EndLatency 和 OffsetExplorer 在抱怨 SLF4J 沒有 Logger 實作

@garyparrot 我已經發了alpha.2，應該已經解決了

**Comment by qoo332001** [comment]
我的linux可以正常運行

**Comment by chia7712** [comment]
我要準備做0.1.0 release，要麻煩大家協助測試各個功能：

1. - [ ] performance (@garyparrot )
1. - [ ] partitioner (@chinghongfang)
1. - [ ] metric (@qoo332001)
1. - [ ] offset explorer (@wycccccc)
1. - [ ] replica collie (@wycccccc) 

請大家測試負責項目的各項參數和功能，並將遇到的錯誤貼上來，謝謝!

**Comment by garyparrot** [comment]
https://github.com/skiptests/astraea/blob/be80c576a54a770cbf8773d9e0902a67f3b1194b/README.md?plain=1#L102-L104

這個參數沒辦法在 main branch 的最新進度上執行。

1. `Performance` 應該弄成 `performance`.
2. `--topicConfig` 已經被移除
3. `--recordSize` -> `--record.size`

https://github.com/skiptests/astraea/blob/be80c576a54a770cbf8773d9e0902a67f3b1194b/README.md?plain=1#L105-L112

這邊的 flag 和目前程式的 argument 有點不一

```
$ ./gradlew run --args="performance --bootstrap.servers localhost:9092 -" 
> Task :app:run
Was passed main parameter '-' but no main parameter was defined in your arg class
Usage: <main class> [options]
  Options:
  * --bootstrap.servers String: server to connect to
    --consumers         Integer: number of consumers to consume records 
                        (default: 1)
    --partitions        Integer: number of partitions to create the topic 
                        (default: 1)
    --producers         Integer: number of producers to produce records 
                        (default: 1)
    --prop.file         String: path to the properties file
    --record.size       Integer: size of each record (default: 1024)
    --records           Integer: number of records to send (default: 1000)
    --replicas          Integer: number of replica to create the topic 
                        (default: 1)
    --topic             String: topic name (default: 
                        testPerformance-1635866419277) 
```

看起來缺了
1. `--producers`
2. `--prop.file`

**Comment by chia7712** [comment]
@garyparrot 感謝測試

@chinghongfang 請幫忙修正~

**Comment by qoo332001** [comment]
3.metric 經測試沒有問題

**Comment by chinghongfang** [comment]
### 2. partitioner
環境：docker/start_broker.sh
使用`astraea.performance`測試`LinkPartitioner`。
**沒有錯誤**，LinkPartitioner有確實執行。

### 實際結果

---
在2-broker集群下，同時執行，使用參數：
```shell
--partitions 1 --records100000000 --record.size 10 
--partitions 3 --records10000000 -- record.size 10
```
結果：
```
topic='4', partition=0, earliestOffset=0, latestOffset=100000000, ... replicas=[Replica{broker=84, ...}]
topic='5', partition=0, earliestOffset=0, latestOffset=5011911, ... replicas=[Replica{broker=451, ...}]
topic='5', partition=1, earliestOffset=0, latestOffset=0, ... replicas=[Replica{broker=84, ...}]
topic='5', partition=2, earliestOffset=0, latestOffset=4988089, ... replicas=[Replica{broker=451, ...}]
```
會發現，`producer`發送資料時，確實避開brokerID 84。效果很好。

**Comment by wycccccc** [comment]
4.offset explorer 經過測試能夠正常顯示topic offset相關信息
5.replica collie 能夠確實的搬移topic

**Comment by garyparrot** [comment]
## prop.file 無法讀取到 working directory 下的東西

後來發現是使用 gradle run 執行 app 時，會把我們的 working directory 移動到 ./astraea/app 裡面。而非將 working directory 設定到目前執行 gradle 的目錄，沒事虛驚一場。

**Comment by chinghongfang** [comment]
@wycccccc 使用LinkPartitioner有時候會出現下面的問題，但不是每次都會出現。不知道原因，在此先紀錄。
```
> java -jar app-0.0.1-SNAPSHOT-all.jar performance --prop.file ./partitioner.properties --bootstrap.servers 192.168.103.26:19846
Exception in thread "pool-2-thread-1" java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at org.astraea.partitioner.partitionerFactory.LinkPartitioner$ThreadSafeSmoothPartitioner.partition(LinkPartitioner.java:95)
	at org.astraea.partitioner.partitionerFactory.SmoothPartitionerFactory$1.partition(SmoothPartitionerFactory.java:58)
	at org.astraea.partitioner.partitionerFactory.LinkPartitioner.partition(LinkPartitioner.java:31)
	at org.apache.kafka.clients.producer.KafkaProducer.partition(KafkaProducer.java:1278)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:931)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:885)
	at org.astraea.producer.Builder$1$1.run(Builder.java:104)
	at org.astraea.performance.Performance$2.execute(Performance.java:160)
	at org.astraea.concurrent.ThreadPool$Builder.lambda$build$0(ThreadPool.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by chia7712** [comment]
@wycccccc 你有看到上面的錯誤嗎？

**Comment by wycccccc** [comment]
有，正在修改ing

**Comment by chia7712** [comment]
暫緩釋出的腳步，等待各個工具都告一個段落
