### ISSUE TITLE
fix TopicHandlerTest#testDeleteTopic

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#533]
```
TopicHandlerTest > testDeleteTopic() FAILED
[2614](https://github.com/skiptests/astraea/runs/7598233860?check_suite_focus=true#step:5:2615)
    org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
[2615](https://github.com/skiptests/astraea/runs/7598233860?check_suite_focus=true#step:5:2616)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[2616](https://github.com/skiptests/astraea/runs/7598233860?check_suite_focus=true#step:5:2617)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:40)
[2617](https://github.com/skiptests/astraea/runs/7598233860?check_suite_focus=true#step:5:2618)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:35)
[2618](https://github.com/skiptests/astraea/runs/7598233860?check_suite_focus=true#step:5:2619)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:227)
[2619](https://github.com/skiptests/astraea/runs/7598233860?check_suite_focus=true#step:5:2620)
        at app//org.astraea.app.web.TopicHandlerTest.testDeleteTopic(TopicHandlerTest.java:216)
```

**Comment by g1geordie** [comment]
小小發問, Is it like `create topic` that brokers need time to sync?

**Comment by chia7712** [comment]
> 小小發問, Is it like create topic that brokers need time to sync?

完全沒錯
