### ISSUE TITLE
Missing stacktrace when using Utils.packException

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#537]
當我使用 Utils.packException 並且遇上Execution exception 的時候
我們會只剩下最內層的Exception 
這導致追蹤錯誤的時候 無法得知 async task 的caller 是誰

範例 
使用 Utils.packException
```
java.lang.IllegalArgumentException: leaving members should not be empty
	at org.apache.kafka.common.requests.LeaveGroupRequest$Builder.<init>(LeaveGroupRequest.java:47)
	at org.apache.kafka.common.requests.LeaveGroupRequest$Builder.<init>(LeaveGroupRequest.java:39)
	at org.apache.kafka.clients.admin.internals.RemoveMembersFromConsumerGroupHandler.buildBatchedRequest(RemoveMembersFromConsumerGroupHandler.java:84)
	at org.apache.kafka.clients.admin.internals.RemoveMembersFromConsumerGroupHandler.buildBatchedRequest(RemoveMembersFromConsumerGroupHandler.java:38)
	at org.apache.kafka.clients.admin.internals.AdminApiHandler$Batched.buildRequest(AdminApiHandler.java:150)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.lambda$collectFulfillmentRequests$5(AdminApiDriver.java:344)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.collectRequests(AdminApiDriver.java:309)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.collectFulfillmentRequests(AdminApiDriver.java:341)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.poll(AdminApiDriver.java:199)
	at org.apache.kafka.clients.admin.KafkaAdminClient.maybeSendRequests(KafkaAdminClient.java:4430)
	at org.apache.kafka.clients.admin.KafkaAdminClient.access$4400(KafkaAdminClient.java:291)
	at org.apache.kafka.clients.admin.KafkaAdminClient$36.handleResponse(KafkaAdminClient.java:4449)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.handleResponses(KafkaAdminClient.java:1262)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1415)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1338)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
直接將execution 用runtime 丟出來 
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: leaving members should not be empty
	at org.astraea.app.common.Utils.packException(Utils.java:77)
	at org.astraea.app.common.Utils.packException(Utils.java:101)
	at org.astraea.app.admin.Builder$AdminImpl.removeAllMembers(Builder.java:555)
	at org.astraea.app.admin.AdminTest.testRemoveEmptyMember(AdminTest.java:912)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: leaving members should not be empty
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at org.astraea.app.admin.Builder$AdminImpl.lambda$removeAllMembers$64(Builder.java:561)
	at org.astraea.app.common.Utils.lambda$packException$0(Utils.java:103)
	at org.astraea.app.common.Utils.packException(Utils.java:71)
	... 88 more
Caused by: java.lang.IllegalArgumentException: leaving members should not be empty
	at org.apache.kafka.common.requests.LeaveGroupRequest$Builder.<init>(LeaveGroupRequest.java:47)
	at org.apache.kafka.common.requests.LeaveGroupRequest$Builder.<init>(LeaveGroupRequest.java:39)
	at org.apache.kafka.clients.admin.internals.RemoveMembersFromConsumerGroupHandler.buildBatchedRequest(RemoveMembersFromConsumerGroupHandler.java:84)
	at org.apache.kafka.clients.admin.internals.RemoveMembersFromConsumerGroupHandler.buildBatchedRequest(RemoveMembersFromConsumerGroupHandler.java:38)
	at org.apache.kafka.clients.admin.internals.AdminApiHandler$Batched.buildRequest(AdminApiHandler.java:150)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.lambda$collectFulfillmentRequests$5(AdminApiDriver.java:344)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.collectRequests(AdminApiDriver.java:309)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.collectFulfillmentRequests(AdminApiDriver.java:341)
	at org.apache.kafka.clients.admin.internals.AdminApiDriver.poll(AdminApiDriver.java:199)
	at org.apache.kafka.clients.admin.KafkaAdminClient.maybeSendRequests(KafkaAdminClient.java:4430)
	at org.apache.kafka.clients.admin.KafkaAdminClient.access$4400(KafkaAdminClient.java:291)
	at org.apache.kafka.clients.admin.KafkaAdminClient$36.handleResponse(KafkaAdminClient.java:4449)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.handleResponses(KafkaAdminClient.java:1262)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1415)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1338)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by g1geordie** [comment]
原本嘗試修改 packException  新增了一個客製Runtime Exception 去取代Runtime Exception 
```
 /**
   * Do not catch AstraeaExecutionRuntimeException , because it is not a stable exception. You can
   * catch it as RuntimeException.
   */
  public static class AstraeaExecutionRuntimeException extends RuntimeException {
    public AstraeaExecutionRuntimeException(Throwable originalException, Throwable rootCause) {
      super(rootCause.getMessage(), rootCause);
      setStackTrace(
          Arrays.stream(new RuntimeException(originalException).getStackTrace())
              .skip(1)
              .toArray(StackTraceElement[]::new));
    }
  }
```


但發現再packException 中 rootCause 為runtime exception是期待直接丟出 而不會包裹的 所以無法達成想要的目的

**Comment by g1geordie** [comment]
@chia7712  這是在撰寫test 時 和 看到 gitlab CI 上的log 時遇到的小麻煩 ><

**Comment by chia7712** [comment]
所以問題其實是看`ExecutionException`這一層要不要補回去？但是在`ExecutionException`這一層再貼一層`RuntimeException`又顯得很多冗余，是否有可能我們建一個自己的unchecked `ExecutionException`來替代Java預設的`ExecutionException`? 這樣可以不用多包一層，然後就避免要處理checked exception?

**Comment by g1geordie** [comment]
假如我定義了一個 AstraeaExecutionRuntimeException  extend RuntimeException 

當ExecutionException 的cause是
1.checked exception 重新包裝 是沒問題的 
`會變成自定的 AstraeaExecutionRuntimeException, getCauser()=the checked exception`
2. Runtime exception 根據method 要求不重新包裝  
`所以我們沒辦法 包裝成 AstraeaExecutionRuntimeException 讓他帶有額外execution的資訊`

所以我們能改變method 要求, 在ExecutionException casue 是Runtime 的時候
讓 RuntimeException 重新包裝成 AstraeaExecutionRuntimeException  , getCauser()=the runtime exception嗎

**Comment by g1geordie** [comment]
就等於說 在處理 ExecutionException 時 不管rootCause 是runtime 還是不是runtime 都會包裝一層
```
if(exception instanceof ExecutionException ){
  var rootCause=....;
  throw new CustomRuntimeException(rootCause);
}else{
  if(exception instacneof RuntimeException){
     throw e ;
  }else{
    new RuntimeException (e)
  }
}
```

**Comment by g1geordie** [comment]
好喔 在麻煩您看看底下的敘述

呼叫了一個 future 的 get method  
`他因為錯誤丟出了 ExecutionException 而裡面的cause 是 illegalArgumentException `
因為 IllegalArgumentException 是 runtime  
`所以我們的 packException 直接向外丟出 illegalArgumentException`

所以我們失去了 executionException 上面相關的 stacktrace

**Comment by chia7712** [comment]
> 所以我們失去了 executionException 上面相關的 stacktrace

根據[上面對話](https://github.com/skiptests/astraea/issues/537#issuecomment-1203944855)，現在是要用`CustomRuntimeException`來包裝`ExecutionException`以便保留 error stack嗎？這個方式看起來可行，應該可以開PR

**Comment by g1geordie** [comment]
closed by #567
