### ISSUE TITLE
Kafka 的 Replication Throttle 似乎不太穩定

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#549]
Context: https://github.com/skiptests/astraea/pull/478#discussion_r938541605

**Comment by chia7712** [comment]
@garyparrot 麻煩在描述裡填上更完整的描述，例如當時是怎麼測試的、觀察的圖等等之類的

**Comment by garyparrot** [comment]
Forward: https://github.com/skiptests/astraea/pull/574#issuecomment-1213724915

我覺得我觸發 https://github.com/skiptests/astraea/issues/549 這個 Replication Throttle 不太穩定的問題了。

現在 AdminTest#runReplicationThrottler 在透過 Gradlew 執行多個 tests 的情況下（不確定這個是不是主要原因，但是我是這樣觸發的），會提早結束，https://github.com/skiptests/astraea/runs/7811763393?check_suite_focus=true 這個測試的結果中，本來應該跑 10 秒的搬移在 1 秒內結束。

我對那個測試做一些修改，現在已經被 Disable 掉，然後內部有 ReplicaSyncingMonitor 檢視負載平衡進度。我們執行下面這個指令 env RunReplicationThrottler=yes ./gradlew test --tests "org.astraea.app.admin.AdminTest.*ReplicationThrottler" --info 來跑這個被 disabled 的測試，我們可以看到

```
AdminTest STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/garyparrot/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-nop/1.7.36/a3c1eb685d59414527faa93623acae311c184032/slf4j-nop-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/garyparrot/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.25/110cefe2df103412849d72ef7a67e4e91e4266b4/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]

AdminTest > runReplicationThrottler() STANDARD_OUT
    [Create topic]
    [Send data]
    [Apply replication throttle]
    [Migration]
    [2022-08-13T13:17:18.48906045]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [                    ]   0.00% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:19.488684125]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  50.69% 102.67 MB/seconds (about now) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:20.488056226]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 5.19 MB/seconds (18s estimated) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:21.487546355]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:22.487176372]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:23.487147631]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:24.486569162]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:25.486400101]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:26.485851236]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:27.485523066]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:28.485224645]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [##########          ]  53.25% 0.00 Byte/seconds (unknown) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:29.484915394]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [################### ]  97.28% 89.19 MB/seconds (about now) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:30.484691694]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [####################]  99.84% 5.19 MB/seconds (about now) []
      | | replica on broker   0 => [####################] 100.00% [leader, synced]

    [2022-08-13T13:17:31.483992089]
      Topic "bd5d82b62bd148e7887ddcc3361fc9f9":
      | Partition 0:
      | | replica on broker   1 => [####################] 100.00% [leader, synced]
      Every replica is synced.

    Finish Time: 14

AdminTest > runReplicationThrottler() FAILED
    org.opentest4j.AssertionFailedError: Migration too fast or too slow? Finish Time:14 second ==> expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at app//org.astraea.app.admin.AdminTest.runReplicationThrottler(AdminTest.java:1575)

Gradle Test Executor 21 finished executing tests.
```

這個情境中是套用 10 MB 限流，資料量 200MB，應該耗費 20 秒左右，不過可以看到搬移過程幾乎是 100 MB 的速度進來，然後 0MB 很長一段時間，在這個不穩的情況下搬移提早結束了。整個過程沒有很平均。

這個是在測試的環境中發現的。因為我們的測試環境很詭異（三個 broker 都在同一個 JVM 內），不確定會不會是這些因素影響的。另外如果我用 IntelliJ 單獨執行這個測試，搬移不會不穩定。

```
[Create topic]
[Send data]
[Apply replication throttle]
[Migration]
[2022-08-13T13:20:29.621402]
  Topic "497b0e64839e4badb78b657a38ecdf55":
  | Partition 0:
  | | replica on broker   1 => [#                   ]   4.10% 0.00 Byte/seconds (unknown) []
  | | replica on broker   0 => [####################] 100.00% [leader, synced]

[2022-08-13T13:20:30.603795]
  Topic "497b0e64839e4badb78b657a38ecdf55":
  | Partition 0:
  | | replica on broker   1 => [#                   ]   5.13% 2.07 MB/seconds (1m 32s estimated) []
  | | replica on broker   0 => [####################] 100.00% [leader, synced]

[2022-08-13T13:20:31.602974]
  Topic "497b0e64839e4badb78b657a38ecdf55":
  | Partition 0:
  | | replica on broker   1 => [#                   ]   8.71% 7.26 MB/seconds (25s estimated) []
  | | replica on broker   0 => [####################] 100.00% [leader, synced]

[2022-08-13T13:20:32.602914]
  Topic "497b0e64839e4badb78b657a38ecdf55":
  | Partition 0:
  | | replica on broker   1 => [##                  ]  13.83% 10.37 MB/seconds (16s estimated) []
  | | replica on broker   0 => [####################] 100.00% [leader, synced]

[2022-08-13T13:20:33.602527]
  Topic "497b0e64839e4badb78b657a38ecdf55":
  | Partition 0:
  | | replica on broker   1 => [###                 ]  18.95% 10.37 MB/seconds (15s estimated) []
  | | replica on broker   0 => [####################] 100.00% [leader, synced]
```

**Comment by chia7712** [comment]
@garyparrot see https://github.com/apache/kafka/pull/12528

**Comment by chia7712** [comment]
@garyparrot 可否開一個PR去給`runReplicationThrottler`補上說明 (參考我上面發的PR)，謝謝
