### ISSUE TITLE
Fix flaky BalancerHandlerTest#testReport

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#653]
```
BalancerHandlerTest > testReport() FAILED
[2529](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2530)
    org.opentest4j.AssertionFailedError: expected: not equal but was: <0>
[2530](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2531)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
[2531](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2532)
        at app//org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:276)
[2532](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2533)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:96)
[2533](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2534)
        at app//org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:88)
[2534](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2535)
        at app//org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:1977)
[2535](https://github.com/skiptests/astraea/runs/8078624618?check_suite_focus=true#step:5:2536)
        at app//org.astraea.app.web.BalancerHandlerTest.testReport(BalancerHandlerTest.java:44)
```

**Comment by chaohengstudent** [comment]
我先處理這個

**Comment by chia7712** [comment]
@chaohengstudent 感謝
