### ISSUE TITLE
Fix flaky testCreateTopics

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#722]
```
TopicHandlerTest > testCreateTopics() FAILED
    org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
        at app//org.astraea.app.web.TopicHandlerTest.testCreateTopics(TopicHandlerTest.java:138)
```

**Comment by brandboat** [comment]
嘗試在 local 跑 @RepeatedTest(10) testCreateTopics

![image](https://user-images.githubusercontent.com/4344302/190842543-d0ca9e45-3f5c-4626-a91a-4f5b51933465.png)

**Comment by chia7712** [comment]
@brandboat 你有打算處理嗎

**Comment by brandboat** [comment]
> @brandboat 你有打算處理嗎

好啊，我試試看
