### ISSUE TITLE
ETL package 無法導入 it package

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#766]
有一個問題想問一下學長，我嘗試在ETL的gradle中配置Astraea it package以創建kafka測試叢集。配置完畢後我的scala似乎就不太正常了。跑測試的時候會報如下錯誤
```
        scala/collection/convert/DecorateAsJava
        java.lang.NoClassDefFoundError: scala/collection/convert/DecorateAsJava
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.astraea.etl.Configuration$.apply(Configuration.scala:75)
```
![螢幕快照 2022-09-26 22-46-58](https://user-images.githubusercontent.com/43372856/192307742-19c24d9b-8f98-404b-82be-6d904f71c316.png)

但我導common package時就沒有問題，我不清楚具體是什麼導致了這個奇怪的現象。

**Comment by chia7712** [comment]
@wycccccc 可否分享你的配置？

**Comment by wycccccc** [comment]
```
plugins {
    // Apply the scala Plugin to add support for Scala.
    id 'scala'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

def versions = [
        scala: project.properties['scala.version'] ?: "2.13.7",
        spark_sql: project.properties['spark_sql.version'] ?: "3.3.0",
        spark_kafka: project.properties['spark_kafka.version'] ?: "3.3.0",
        junit: project.properties['junit.version'] ?: "5.8.2",
        scalatest: project.properties['scalatest.version'] ?: "3.1.1",
        opencsv: project.properties['opencsv.version'] ?: "4.1",
        kafka: project.properties['kafka.version'] ?: "3.2.1"
]

dependencies {
    implementation "org.scala-lang:scala-library:${versions["scala"]}"
    implementation "org.apache.spark:spark-sql_2.13:${versions["spark_sql"]}"
    implementation "org.apache.spark:spark-sql-kafka-0-10_2.13:${versions["spark_kafka"]}"
    implementation "org.apache.kafka:kafka-clients:${versions["kafka"]}"

    testImplementation "org.scalatest:scalatest_2.13:${versions["scalatest"]}"
    testImplementation "org.junit.jupiter:junit-jupiter:${versions["junit"]}"
    testImplementation "com.opencsv:opencsv:${versions["opencsv"]}"
    testImplementation project(':common')
    testImplementation project(':it')
}

ext {
    numberOfForks = project.hasProperty('maxParallelForks') ? maxParallelForks.toInteger() : Math.max((int) (Runtime.runtime.availableProcessors() / 2), 1)
}

archivesBaseName = "astraea-etl"

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    maxParallelForks = numberOfForks
    // make isolation for tests. It may be expensive but stability is first choice.
    forkEvery = 1
    testLogging {
        events "PASSED", "STARTED", "FAILED", "SKIPPED"
        exceptionFormat = 'full'
    }

    minHeapSize = "512m"
    maxHeapSize = "2048m"
}
```

問題應該是由   ` testImplementation project(':it')`導致的

**Comment by chia7712** [comment]
@wycccccc https://github.com/skiptests/astraea/pull/779#issuecomment-1259535050 please take a look

**Comment by wycccccc** [comment]
好 我再統一使用scala 2.12
