### ISSUE TITLE
Fix flaky BalancerTest#testLeaderCountRebalance

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#815]
```
BalancerTest > testLeaderCountRebalance(boolean) > org.astraea.common.balancer.BalancerTest.testLeaderCountRebalance(boolean)[2] FAILED
[1925](https://github.com/skiptests/astraea/actions/runs/3170979302/jobs/5163990367#step:5:1926)
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
[1926](https://github.com/skiptests/astraea/actions/runs/3170979302/jobs/5163990367#step:5:1927)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[1927](https://github.com/skiptests/astraea/actions/runs/3170979302/jobs/5163990367#step:5:1928)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
[1928](https://github.com/skiptests/astraea/actions/runs/3170979302/jobs/5163990367#step:5:1929)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
[1929](https://github.com/skiptests/astraea/actions/runs/3170979302/jobs/5163990367#step:5:1930)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
[1930](https://github.com/skiptests/astraea/actions/runs/3170979302/jobs/5163990367#step:5:1931)
        at app//org.astraea.common.balancer.BalancerTest.testLeaderCountRebalance(BalancerTest.java:97)
```

**Comment by chia7712** [comment]
fixed by #823
