### ISSUE TITLE
Fix flaky KafkaWriterTest#TopicCreatorTest

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#878]
```
KafkaWriterTest > TopicCreatorTest() FAILED
[3882](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3883)
    java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[3883](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3884)
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[3884](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3885)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
[3885](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3886)
        at org.astraea.etl.KafkaWriterTest.$anonfun$TopicCreatorTest$2(KafkaWriterTest.scala:49)
[3886](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3887)
        at org.astraea.etl.Utils$.Using(Utils.scala:53)
[3887](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3888)
        at org.astraea.etl.KafkaWriterTest.TopicCreatorTest(KafkaWriterTest.scala:40)
[3888](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3889)

[3889](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3890)
        Caused by:
[3890](https://github.com/chia7712/astraea/actions/runs/3227554064/jobs/5282508373#step:5:3891)
        org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```

**Comment by chia7712** [comment]
@wycccccc 麻煩看一下喔，這隻測試頻繁的失敗

**Comment by wycccccc** [comment]
好 我現在修一下。

**Comment by chia7712** [comment]
fixed by #896
