### ISSUE TITLE
Fix flaky BalancerAlgorithmTest

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#881]
```
BalancerAlgorithmTest > test() > org.astraea.common.balancer.BalancerAlgorithmTest.test()[2] FAILED
[1660](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1661)
    org.astraea.common.ExecutionRuntimeException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[1661](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1662)
        at app//org.astraea.common.Utils.packException(Utils.java:62)
[1662](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1663)
        at app//org.astraea.common.admin.Builder$AdminImpl.topicPartitions(Builder.java:180)
[1663](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1664)
        at app//org.astraea.common.admin.Builder$MigratorImpl.topic(Builder.java:679)
[1664](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1665)
        at app//org.astraea.common.balancer.BalancerAlgorithmTest.lambda$test$1(BalancerAlgorithmTest.java:41)
[1665](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1666)
        at java.base@11.0.11/java.util.HashMap$KeySet.forEach(HashMap.java:928)
[1666](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1667)
        at app//org.astraea.common.balancer.BalancerAlgorithmTest.test(BalancerAlgorithmTest.java:41)
[1667](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1668)

[1668](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1669)
        Caused by:
[1669](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1670)
        java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[1670](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1671)
            at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[1671](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1672)
            at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
[1672](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1673)
            at org.astraea.common.admin.Builder$AdminImpl.lambda$topicPartitions$10(Builder.java:181)
[1673](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1674)
            at org.astraea.common.Utils.packException(Utils.java:58)
[1674](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1675)
            ... 5 more
[1675](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1676)

[1676](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1677)
            Caused by:
[1677](https://github.com/skiptests/astraea/actions/runs/3229379803/jobs/5286608795#step:5:1678)
            org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```

**Comment by chia7712** [comment]
resolved by #911
