### ISSUE TITLE
Fix flaky AsyncAdminTest#testPendingRequest

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#933]
```
AsyncAdminTest > testPendingRequest() FAILED
[1664](https://github.com/skiptests/astraea/actions/runs/3259868675/jobs/5353011796#step:5:1665)
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
[1665](https://github.com/skiptests/astraea/actions/runs/3259868675/jobs/5353011796#step:5:1666)
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[1666](https://github.com/skiptests/astraea/actions/runs/3259868675/jobs/5353011796#step:5:1667)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
[1667](https://github.com/skiptests/astraea/actions/runs/3259868675/jobs/5353011796#step:5:1668)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
[1668](https://github.com/skiptests/astraea/actions/runs/3259868675/jobs/5353011796#step:5:1669)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
[1669](https://github.com/skiptests/astraea/actions/runs/3259868675/jobs/5353011796#step:5:1670)
        at app//org.astraea.common.admin.AsyncAdminTest.testPendingRequest(AsyncAdminTest.java:1185)
```

**Comment by chia7712** [comment]
@chaohengstudent 麻煩看一下，我猜可能是執行得太快導致 pendingRequests 回傳 0
