### ISSUE TITLE
Fix Flaky `RecordHandlerTest#testDelete()`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#961]
Source https://github.com/skiptests/astraea/actions/runs/3282393763/jobs/5405739787#step:5:714
```
RecordHandlerTest > testDelete() FAILED
    org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:628)
        at app//org.astraea.app.web.RecordHandlerTest.testDelete(RecordHandlerTest.java:807)
```

**Comment by garyparrot** [comment]
剛剛測試這個在 #945 修好了
